name=ES32D26PLC
version=1.1.0
author=JDavid
maintainer=JDavid
sentence=Library for controlling ES32D26 PLC board with relays, inputs, and analog I/O.
paragraph=Provides functions to manage relay outputs, digital inputs, free outputs, analog inputs/outputs, and utilities for ES32D26 PLC boards. Designed to work with Arduino, ESP32 Arduino, and ESP-IDF (Arduino as component).
category=Device Control
url=https://github.com/blackhack/ES32D26PLC
architectures=esp32
